name: mypy
on: [push]
jobs:
  type-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:master
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install --break-system-packages --ignore-installed .
      - name: Run mypy
        run: mypy truenas_crypto_utils/ truenas_acme_utils/
